{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geomtextpath
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geomtextpath_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geomtextpath/geomtextpath_{{ version }}.tar.gz
  sha256: e0afa0472f5abb5f4a0ebd587ba928953cd574434b1731f9fb92d66a763758dd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-rlang
    - r-scales
    - r-systemfonts
    - r-textshaping
  run:
    - r-base
    - r-ggplot2
    - r-rlang
    - r-scales
    - r-systemfonts
    - r-textshaping

test:
  commands:
    - $R -e "library('geomtextpath')"           # [not win]
    - "\"%R%\" -e \"library('geomtextpath')\""  # [win]

about:
  home: https://allancameron.github.io/geomtextpath/
  license: MIT
  summary: A 'ggplot2' extension that allows text to follow curved paths. Curved text makes it easier to directly label paths or neatly annotate in polar co-ordinates.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
